### PR TITLE
Set default ZarrPlugin prefix to /zarr

### LINKED ISSUE #182: Set zarr router prefix
We should set a default prefix for the Zarr router plugin. Otherwise it often wants to eat the requests to other dataset routers.

Brought up by @kwilcox during the community meeting #172 and @jhamman gave a thumbs up to make the change. 

I'll assign myself to make sure it gets done before the next release, but if someone else gets to it first, go for it. 

It should be changing the prefix here:

https://github.com/xarray-contrib/xpublish/blob/feff2c44ad9e533adf41753c29a0c16544d2868c/xpublish/plugins/included/zarr.py#L21-L30

to`dataset_router_prefix: str = '/zarr'`and then cleaning up the tests.

### PR DESCRIPTION
**Pull request by abkfenris**
Closes #182

### CODE REVIEW

**Comment by abkfenris** [comment]
@jhamman I might need some Zarr help here. It looks like it's failing as the non-dimension coordinate order [isn't matching in the metadata](https://github.com/xpublish-community/xpublish/actions/runs/4833414440/jobs/8613392327?pr=188#step:6:3417) tests. 

I haven't been able to replicate it against Python 3.9.15, Xarray 2023.4.2,  Zarr  2.14.2 (or 2.11.3 before I bumped Zarr to see if that was mismatched) locally. I didn't see anything in Xarray or Zarr's changelog that made me think that there would be a change in either that would affect the ordering of `lat` and `lon`.

**Review by jhamman — APPROVED** [review]

**Comment by jhamman** [comment]
I re-triggered the failed CI and things past. Not sure what was up with the previous failed run but I'm wondering if it had picked up an old/malformed cache.

**Comment by jhamman** [comment]
Oh, do we need some doc updates with this?

**Comment by abkfenris** [comment]
It just [failed the same way](https://github.com/xpublish-community/xpublish/actions/runs/4838170802/jobs/8622475139#step:6:6396) when landing the pydata-theme PR. I'm going to try explicitly sorting the coord names to see if that helps make the ordering of coords predictable at least from Xpublish's side.

And yes, because I had big doc changes in flight I'm going to make the updates there #180.

**Comment by abkfenris** [comment]
Ok, so [we are sorting coordinates](https://github.com/xpublish-community/xpublish/actions/runs/4838465300/jobs/8622930986?pr=188#step:6:3442), but Xarray/Zarr isn't?

**Comment by abkfenris** [comment]
And that also passes when run again.

**Comment by abkfenris** [comment]
It looks like xarray sets the value here, and I can't make out any sorting which would make it stable. https://github.com/pydata/xarray/blob/25d9a28e12141b9b5e4a79454eb76ddd2ee2bc4d/xarray/conventions.py#L690-L697

**Pull request merged**
